containers:
    - name: hello-world
      image: hashicorp/http-echo@sha256:fcb75f691c8b0414d670ae570240cbf95502cc18a9ba57e982ecac589760a186
      args: []
      env:
        - LOG_LEVEL=info
      secrets:
        - API_KEY
memory: 8192
cpus: 4
gpus: 0
